import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { useState } from "react";
import Image from "next/image";
import { prefix } from "../utils/prefix";
import kml from "../public/my-cartoon-2.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
export default function Home() {
  const [darkMode, setDarkMode]=useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kamala Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">developedbyKML</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill  onClick={()=> setDarkMode(!darkMode)} className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-700  text-white px-4 py-2 rounded-md ml-8"
                  href="https://www.linkedin.com/in/kemale-shamilova-57675018a/"  
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center pb-10">
            <h2 className="text-4xl pb-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400 ">
              Kamala Shamilova
            </h2>
            <h3 className="py-2 text-2xl md:text=3xl dark:text-teal-200 ">React js Developer</h3>
            <p className="text-medium py-5 leading-8 text-gray-800 dark:text-teal-200  md:text-xl max-w-xl mx-auto">
              Freelancer providing services for programming and design content
              needs
            </p>
          </div>
          <div className="text-5xl justify-center flex gap-10 py-3 text-gray-600 dark:text-orange-500 ">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-cyan-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:w-96 md:h-96">
            <Image  src={`${prefix}/my-cartoon-2.png`} layout="fill" objectFit="cover" alt="hero"/>
          </div>
        </section>

        <section>
          <div>
              <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 ">I
               worked at many companies as
                a <span className="text-cyan-600"> Frontend </span> 
                developer. </p>
                <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 ">
              I offer from a wide range of services, including brand design,
              programming and teaching .
            </p>
          </div>
          <div className="md:flex gap-10">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image src={design } width={100} height={100}/>
            <h3>Beautiful Designs</h3>
            <p>Creating elegant design suited for your needs following core
                design theory.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 ">Photoshop</p>
              <p className="text-gray-800 py-1 ">Illustrator</p>
              <p className="text-gray-800 py-1 ">Figma</p>
              <p className="text-gray-800 py-1 ">Indesign</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 ">
            <Image src={consulting } width={100} height={100}/>
            <h3>Beautiful Designs</h3>
            <p>Creating elegant design suited for your needs following core
                design theory.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 ">
            <Image src={code } width={100} height={100}/>
            <h3>Beautiful Designs</h3>
            <p>Creating elegant design suited for your needs following core
                design theory.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
          </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I
               worked at many companies as
                a <span className="text-cyan-600"> Frontend </span> 
                developer. </p>
                <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 ">
              I offer from a wide range of services, including brand design,
              programming and teaching .
            </p>  
          </div>
          <div className="flex flex-col gap-10 py-10 md:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1"> <Image src={web1} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"> <Image src={web2} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"> <Image src={web3} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"> <Image src={web4} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"> <Image src={web5} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>
            <div className="basis-1/3 flex-1"> <Image src={web6} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /></div>
          </div>
        </section>
      </main>
    </div>
  );
}
